### ISSUE TITLE
Add Integration Tests for NPGSQL 4.1 changes

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/ecss-10-25-annexc-integration-tests#25]
Add integration tests for the changes done for the Npgsql 4.1 upgrade.

**Comment by lxatrhea** [comment]
Docker container commands:
- docker build C:\users\avandelft\source\repos\CDP4-Docker\cdp4-database-bare-community-edition -t cdp4-test-database-community-edition:1.4.0
- docker run -p 5436:5432 --tmpfs /var/lib/postgresql/data -it -d -e POSTGRES_PASSWORD=password --name cdp4-test-database-community-edition-postgres12 cdp4-test-database-community-edition:1.4.0

**Comment by samatrhea** [comment]
> 
> 
> Docker container commands:
> 
>     * docker build C:\users\avandelft\source\repos\CDP4-Docker\cdp4-database-bare-community-edition -t cdp4-test-database-community-edition:1.4.0
> 
>     * docker run -p 5436:5432 --tmpfs /var/lib/postgresql/data -it -d -e POSTGRES_PASSWORD=password --name cdp4-test-database-community-edition-postgres12 cdp4-test-database-community-edition:1.4.0

Hi, lets not put pathnames of your personal user profile in a command, the way to go is:

  - change directory to where the Dockerfile is located
  - docker build  -t cdp4-test-database-community-edition:1.4.0 .

=> check the `.` at the end of the command

**Comment by samatrhea** [comment]
also check
  - https://hub.docker.com/repository/docker/rheagroup/cdp4-test-database-community-edition
  - https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/wiki/Dockerize

**Comment by lxatrhea** [comment]
Thanks. I missed the dot.
