### ISSUE TITLE
Update setup wiki page to mention missing server configurations needed to run integration tests

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/ecss-10-25-annexc-integration-tests#29]
In order to be able to run the integration tests, the server configuration (be it locally or in a docker container) needs to be updated with the following two settings:
```
    "IsDbSeedEnabled": true,
    "IsDbRestoreEnabled": true
```

> Make sure that the URL of the database is known to the CDP4® Services by updating the settings.json file of the CDP4® Services project.

There is no "settings.json" file in the CDP4 Services project.

### Tasks
* [x] mention IsDbSeedEnabled & IsDbRestoreEnabled
* [x] update reference to "settings.json" file

**Comment by samatrhea** [comment]
these settings should not be the default in the container that we distribute for production use. So, just do it locally for testing purposes please

**Comment by cozminvelciu** [comment]
> these settings should not be the default in the container that we distribute for production use. So, just do it locally for testing purposes please

Of course, I just wanted to point out that for the integration tests setup wiki page, these need to be mentioned. Indeed, they should not be included in any release image.

**Comment by cozminvelciu** [comment]
> updating the settings.json file of the CDP4® Services project.

There seems to be no "settings.json" file, only "config.json".

**Comment by lxatrhea** [comment]
@cozminvelciu looks good to me
